[package]
name = "foster"
version = "0.1.0"
edition = "2024"
description = "The bootstrap implementation of the Foster programming language"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "foster"
path = "src/main.rs"

[dependencies]
ariadne = "0.6"
camino = "1.2"
clap = "4.6.6"
la-arena = "0.3"
lsp-server = "0.10"
lsp-types = "0.97"
may = "0.3.51"
pulldown-cmark = "0.13.4"
serde_json = "1"
walkdir = "2.5"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "compiler"
harness = false

[[bench]]
name = "runtime"
harness = false
